# debug: false
remote_configuration: true
# instance_name: default
# flags:
#   no_logo: false
#   no_start: false
#   no_connect: false
#   no_share_scan: false
#   no_version_check: false
#   log_sql: false
# directories:
#   incomplete: ~
#   downloads: ~
#   shared:
#     - ~
# rooms:
#   - ~
# global:
#   upload:
#     slots: 20
#     speed_limit: 1000
#   download:
#     slots: 500
#     speed_limit: 1000
# groups:
#   default:
#     upload:
#       priority: 500
#       strategy: roundrobin
#       slots: 10
#   leechers:
#     thresholds:
#       files: 1
#       directories: 1
#     upload:
#       priority: 999
#       strategy: roundrobin
#       slots: 1
#       speed_limit: 100
#   user_defined:
#     my_buddies:
#       upload:
#         priority: 250
#         queue_strategy: firstinfirstout
#         slots: 10
#       members:
#         - alice
#         - bob
# filters:
#   share:
#     - \.ini$
#     - Thumbs.db$
#     - \.DS_Store$
#   search:
#     request:
#       - ^.{1,2}$
# web:
#   port: 5000
#   https:
#     disabled: false
#     port: 5001
#     force: false
#     certificate:
#       pfx: ~
#       password: ~
#   url_base: /
#   content_path: wwwroot
#   logging: false
#   authentication:
#     disabled: false
#     username: slskd
#     password: slskd
#     jwt:
#       key: ~
#       ttl: 604800000
# logger:
#   loki: ~
# feature:
#   prometheus: false
#   swagger: false
# soulseek:
#   username: ~
#   password: ~
#   description: |
#     A slskd user. https://github.com/slskd/slskd
#   listen_port: 50000
#   diagnostic_level: Info
#   distributed_network:
#     disabled: false
#     disable_children: false
#     child_limit: 25
#     logging: false
#   connection:
#     timeout:
#       connect: 10000
#       inactivity: 15000
#     buffer:
#       read: 16384
#       write: 16384
#       transfer: 262144
#       write_queue: 250
#     proxy:
#       enabled: false
#       address: ~
#       port: ~
#       username: ~
#       password: ~
# integration:
#   ftp:
#     enabled: false
#     address: ~
#     port: ~
#     username: ~
#     password: ~
#     remote_path: /
#     encryption_mode: auto
#     ignore_certificate_errors: false
#     overwrite_existing: true
#     connection_timeout: 5000
#     retry_attempts: 3
#   pushbullet:
#     enabled: false
#     access_token: ~
#     notification_prefix: "From slskd:"
#     notify_on_private_message: true
#     notify_on_room_mention: true
#     retry_attempts: 3
#     cooldown_time: 900000
